Corrected build instructions; 跟新了编译文档
solosky/pixl.js pull request #126
Opened 2023-10-30 17:04 UTC by fishybow

Corrected build instructions, corrected a few minor mistakes.

跟新了编译文档，之前的指令有一些小错误。

2023-11-05 06:35 UTC, solosky requested changes

2023-11-05 06:35 UTC, solosky commented on README.md
> +root@b10d54636088:/builds/pixl.js/fw# pushd application && make full ota; popd
pushd popd 是什么指令？我的bash不支持，建议删除

2023-11-05 17:14 UTC, fishybow reviewed
Removed pushd and popd.

2023-11-06 14:19 UTC, merged

2023-11-06 14:20 UTC, solosky commented
Thanks for your contrubition.