Add Russian language support
solosky/pixl.js pull request #221
Opened 2024-03-20 16:59 UTC by hummer007

Russian language has been added to the language options in the internationalization files. New entries for Russian (ru) have been made in each of the existing language files and a new language file has been created specifically for Russian (ru_RU.js). The dropdown for language selection in the App has been updated to include this new option.

2024-03-23 14:45 UTC, solosky requested changes
please see my comments.

2024-03-23 14:45 UTC, solosky commented on web/src/i18n/ru_RU.js
> +        choose: 'Выбор языка/Language',
Please do not translate language display name. 
The language selection should be keep its original translation for user select in any language profile.

2024-03-26 12:09 UTC, merged

2024-03-26 12:09 UTC, solosky commented
Thanks!

2024-03-27 09:43 UTC, MayanKoyote commented
Just add a bit of meaning to these lines, otherwise it looks like classic machine translation nonsense.
At least something like this:

1. https://github.com/solosky/pixl.js/blob/5b85e4ccdcd30e2a6244680db0877fbbe9620da7/web/src/i18n/ru_RU.js#L9
     changeok: 'Успешно сменить язык',
     -> changeok: 'Переключение языка прошло успешно!',

2. https://github.com/solosky/pixl.js/blob/5b85e4ccdcd30e2a6244680db0877fbbe9620da7/web/src/i18n/ru_RU.js#L95
     message: 'Версия встроенного ПО вашего устройства слишком низкая. Пожалуйста, обновите последнюю версию ПО перед использованием функции загрузки.'
    -> message: 'Версия встроенного ПО вашего устройства слишком старая. Пожалуйста, обновитесь до последней версии ПО перед использованием функции загрузки.'

2024-03-27 10:05 UTC, hummer007 commented
> Just add a bit of meaning to these lines, otherwise it looks like classic machine translation nonsense. At least something like this:
> 
> 1. https://github.com/solosky/pixl.js/blob/5b85e4ccdcd30e2a6244680db0877fbbe9620da7/web/src/i18n/ru_RU.js#L9
>    
>    -> changeok: 'Переключение языка прошло успешно!',
> 2. https://github.com/solosky/pixl.js/blob/5b85e4ccdcd30e2a6244680db0877fbbe9620da7/web/src/i18n/ru_RU.js#L95
>    
>    -> message: 'Версия встроенного ПО вашего устройства слишком старая. Пожалуйста, обновитесь до последней версии ПО перед использованием функции загрузки.'

I'm going to modify and make a PR.

2024-03-27 10:22 UTC, hummer007 commented
@MayanKoyote you can check this [PR](https://github.com/solosky/pixl.js/pull/227)