added Italian Translation of notes (amiibo_db_link)
solosky/pixl.js pull request #235
Opened 2024-04-02 12:21 UTC by JostenSyon

Added All zelda related notes for Italian language by using proper note_it, comment on auto-generated content to prevent editing it my mistake

2024-04-02 14:46 UTC, solosky requested changes
Thank your contribution on this!

The PR  looks good for me and I could merge to develop branch ready for next release. 

More and more contributors are offering support in various languages, and I am very grateful for their support. However, at the same time, this multi language support will increase the maintenance cost of this project. For example, adding text for new features requires translation work. 

Unfortunately, I am unable to provide translation and maintenance work for additional languages. I am considering whether to stop accepting more language merge requests in the future because I may not be able to maintain these languages. 

I can only provide language support in Chinese and English.

2024-04-02 14:49 UTC, JostenSyon commented on README.md
> +Fork progetto originale [Pixl.js](http://www.espruino.com/Pixl.js)
really sorry, committed by mistake, right now i'm doing a proper docs /it/ documentation ;)

2024-04-02 15:00 UTC, JostenSyon commented on README.md
> +Fork progetto originale [Pixl.js](http://www.espruino.com/Pixl.js)
btw, when, and I hope will be not necessary, you will need some space due too many languages, I can contribute to make an EU firmware to give some free space ;) (at least for IT-ES-FR-EN there is no problem for me)

2024-04-02 15:10 UTC, solosky commented on README.md
> +Fork progetto originale [Pixl.js](http://www.espruino.com/Pixl.js)
if you say "space" means available flash memory, that's not an issue currently, we still have around 30K available flash memory for new features and language files. 

BTW, I am working on new hardware version with more flash memory (1M) and new RC522 reader chip on it, there will be new feature added in firmware, I may need your support to translation text to IT-ES-FR in future..

2024-04-03 14:35 UTC, solosky approved these changes
LGTM

2024-04-03 14:36 UTC, merged

2024-04-03 14:37 UTC, solosky commented
Thanks, I will release new firmware version next week.

2024-04-03 17:29 UTC, JostenSyon commented
I’m ready for an main-eu firmware 😂

Il giorno mer 3 apr 2024 alle 19:23 MayanKoyote ***@***.***>
ha scritto:

> firmware size increased 6912 bytes...
>
> Apparently the time for different firmware for different geographical
> regions is approaching. Just like Nintendo cartridges with different sets
> of languages.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/solosky/pixl.js/pull/235#issuecomment-2035171972>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMTI3PWW7DTRWBNIGO67EDY3Q3HVAVCNFSM6AAAAABFTI6DCKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMZVGE3TCOJXGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>