Fixing some English translations
solosky/pixl.js pull request #252
Opened 2024-05-09 05:03 UTC by x-magic

There has been a lot of upstream updates since my previous PR so I thought it's time to update! 

Mainly focused on the interpretation quality and use of language. A few cosmetic changes (such as "File Transfer" in BLE screen as there's already a BT icon in front of it), too. 

我先放draft PR吧，我得再过一遍UI看看还有没有要改的地方。屏幕太小了很多地方不太能挤得下。而且最近才有的二奶机，终于舍得为了一些字串而重置设置和格式化了😏

2024-05-09 05:11 UTC, solosky commented
感谢贡献，友情提醒下：需要把i8n.csv的修改提到PR里面。

2024-05-17 01:02 UTC, x-magic commented
> 感谢贡献，友情提醒下：需要把i8n.csv的修改提到PR里面。

改好了，润色也在实机测试过了

2024-05-20 13:50 UTC, solosky requested changes
一些小的修改建议

2024-05-20 13:50 UTC, solosky commented on fw/application/src/i18n/en_US.c
> +    [_L_APP_CHAMELEON_CARD_DATA_LOAD] = "Load Card Data...",
建议保留 Load.. 和 Save.. 后面加card data 感觉有点多余，也不能强调是Load还是Save

2024-05-20 13:50 UTC, solosky commented on fw/application/src/i18n/en_US.c
> +    [_L_KNOW] = "Understood",
建议改成OK

2024-05-20 13:50 UTC, solosky commented on fw/application/src/i18n/en_US.c
> +    [_L_APP_BLE_TITLE] = " File Transfer",
多了一个空格

2025-08-07 06:33 UTC, wkelebn commented
[加入繁中amiidb_game.zip](https://github.com/user-attachments/files/21654789/amiidb_game.zip)
我加了一些繁中，希望幫得上幫

2026-04-11 07:13 UTC, x-magic commented
Sorry I really don't have time contributing on this for the foreseeable future so I'm going to close this PR. Hopefully one day I'll be able to pick it up again. Thank you solosky and everyone else's support.

2026-04-11 07:13 UTC, closed without merging