Enhance
solosky/pixl.js pull request #61
Opened 2023-04-16 11:54 UTC by 577fkj

2023-04-16 15:38 UTC, solosky requested changes
感谢贡献！

不过不是很建议把内存保存在磁盘来做快速恢复，建议参考下nrf52832的手册，把ram其中一块区域设置为不掉电来保存应用的数据，在app层处理好数据保存和恢复。

你可以看下这方面的内容。 可参考的代码有 https://github.com/RfidResearchGroup/ChameleonUltra

2023-04-16 15:38 UTC, solosky commented on fw/src/mui/mui_core.c
> +    if (cache->enabled && cache->current_file != "") {
用strcmp

2023-04-16 15:38 UTC, solosky commented on fw/src/main.c
> +static void ntag_gen(ntag_t *ntag_current) {
删除这个方法，使用 amiibo_helper_ntag_generate

2023-04-16 15:38 UTC, solosky commented on fw/src/mod/cache.c
> +    if (m_cache_data.current_file == "" || m_cache_data.current_folder == "" || m_cache_data.current_drive == VFS_DRIVE_MAX) {
用strcmp比较字符串

2023-04-16 15:38 UTC, solosky commented on fw/src/mod/cache.c
> +void weak_up_set_lcdled(bool on) {
建议去掉这个逻辑，频繁休眠会导致flash磨损加快，应该尽量减少flash的写入

2023-04-16 15:38 UTC, solosky commented on fw/src/mui/mui_input.c
> +        weak_up_set_lcdled(false);
去掉这个逻辑

2023-04-16 15:38 UTC, solosky commented on fw/src/mod/cache.c
> +    if (m_cache_data.current_drive != VFS_DRIVE_MAX && m_cache_data.current_folder != "" && m_cache_data.current_file != "") {
用Strcmp比较字符串

2023-04-17 11:57 UTC, 577fkj commented on fw/src/mui/mui_core.c
> +    if (cache->enabled && cache->current_file != "") {
已按照要求修改

2023-04-17 11:57 UTC, 577fkj commented on fw/src/main.c
> +static void ntag_gen(ntag_t *ntag_current) {
已按照要求修改

2023-04-17 11:59 UTC, 577fkj commented on fw/src/main.c
> +static void ntag_gen(ntag_t *ntag_current) {
已按照要求修改

2023-04-17 11:59 UTC, 577fkj commented on fw/src/mod/cache.c
> +void weak_up_set_lcdled(bool on) {
已按照要求修改

2023-04-17 11:59 UTC, 577fkj commented on fw/src/mui/mui_input.c
> +        weak_up_set_lcdled(false);
已按照要求修改

2023-04-17 11:59 UTC, 577fkj commented on fw/src/mod/cache.c
> +    if (m_cache_data.current_drive != VFS_DRIVE_MAX && m_cache_data.current_folder != "" && m_cache_data.current_file != "") {
已按照要求修改

2023-04-17 11:59 UTC, 577fkj commented on fw/src/mod/cache.c
> +    if (m_cache_data.current_file == "" || m_cache_data.current_folder == "" || m_cache_data.current_drive == VFS_DRIVE_MAX) {
已按照要求修改

2023-04-19 03:38 UTC, 577fkj commented
已经把缓存数据保存在不断电ram内，请检查代码，如果没问题可以进行合并了

2023-04-19 15:15 UTC, solosky requested changes
这一块的实现还是不够好。 

在mini_app_inst_t这个对象里面我保留了一retain_data字段，这个字段之前的设想就来实现app的休眠和恢复的，休眠和恢复的实现都应该委托给app去完成数据保存和读取。

## 关机流程
在系统将要关机时，launcher调用app的kill方法，然后app自行把需要保存的数据放在retain_data这个字段里面，然后由launcher保存在cache中，同时也把当前的app id放在cache中。

## 开机流程 
在launcher加载应用前，判断cache中是否有上一次保存的应用的数据，如果有从cache中读取出来，放在retain_data里面，然后调用app的run方法，由app的run方法来确定应该跳转到哪个页面。

上面的流程是按app休眠恢复的思路实现的。建议按这个思想实现就比较优雅了。 也不需要这个next_tick的trick了。

PS: next_tick也可以通过post_event到事件队列里面来实现延迟处理逻辑。

2023-04-19 15:18 UTC, solosky commented
还有个比较大的BUG: 系统休眠然后唤醒后，NFC读取不出来数据，用手机NFC Tools应用也无法读取。

2023-04-24 06:21 UTC, closed without merging